config/routes.rb
Rails.application.routes.draw do

  get 'passthrough/index'

  get 'income/new', to: 'income#new'
  get 'income/show', to: 'income#show'
  get 'income/edit', to: 'income#edit'
  get 'incomes/', to: 'income#index'

  resources :categories
  resources :payments
  resources :accounts
  resources :articles
  resources :items
  resources :vendors
  resources :baskets
  resources :income

  get 'welcome/index'
  get 'landing/index'
  get 'landing/help'

  devise_for :users

  root 'passthrough#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  has_many :payments
  validates :number, :bic, :name, :user_id, presence: true

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  has_many :items
  validates :name, :price, :active, presence: true
  validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }
end

app/models/basket.rb
class Basket < ActiveRecord::Base
  belongs_to :user
  belongs_to :payment
  belongs_to :vendor
  has_many :items, :dependent => :destroy
  accepts_nested_attributes_for :items, :allow_destroy => true
  validates :amount, :user_id, :vendor_id, :purchase_date, :payment_id, presence: true
  validates :amount, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }

  mount_uploader :document, DocumentUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  belongs_to :glyphicon
  validates :name, :user_id, presence: true
end

app/models/glyphicon.rb
class Glyphicon < ActiveRecord::Base
  has_many :categories
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :basket
  belongs_to :category
  belongs_to :article
  belongs_to :user
  validates :name, presence: true
  validates :category_id, :user_id, :price,  presence: true
  validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
  has_many :basket
  validates :name, :bic, :number, :user_id, presence: true
end

app/models/period.rb
class Period < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :baskets
  has_many :categories
  has_many :payments
  has_many :items
  has_many :vendors
  #attr_accessor :email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:email]
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'


end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_many :baskets
  belongs_to :user
  validates :name, :user_id, presence: true


  mount_uploader :logo, DocumentUploader


end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :set_basket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html

  def index
    @baskets = Basket.where(:user_id => current_user.id)

    year = Time.now.year
    @chartBaskets = LazyHighCharts::HighChart.new('graph') do |f|
      f.options[:xAxis][:categories] = ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September','Oktober', 'November', 'Dezember']
      f.series(:type=> 'column',:name=> 'Ausgaben',  :showInLegend => false, :data=> [ sum_amount(find_basket_for_time_period("01-01-#{year}","01-31-#{year}")),
                                                             sum_amount(find_basket_for_time_period("02-01-#{year}","02-28-#{year}")),
                                                             sum_amount(find_basket_for_time_period("03-01-#{year}","03-31-#{year}")),
                                                             sum_amount(find_basket_for_time_period("04-01-#{year}","04-30-#{year}")),
                                                             sum_amount(find_basket_for_time_period("05-01-#{year}","05-31-#{year}")),
                                                             sum_amount(find_basket_for_time_period("06-01-#{year}","06-30-#{year}")),
                                                             sum_amount(find_basket_for_time_period("07-01-#{year}","07-31-#{year}")),
                                                             sum_amount(find_basket_for_time_period("08-01-#{year}","08-31-#{year}")),
                                                             sum_amount(find_basket_for_time_period("09-01-#{year}","09-30-#{year}")),
                                                             sum_amount(find_basket_for_time_period("10-01-#{year}","10-31-#{year}")),
                                                             sum_amount(find_basket_for_time_period("11-01-#{year}","11-30-#{year}")),
                                                             sum_amount(find_basket_for_time_period("12-01-#{year}","12-31-#{year}")),])
      f.options[:chart][:backgroundColor] = 'rgba(0, 0, 0, 0)'
    end

    respond_with(@baskets)
  end

  def show
    respond_with(@basket)
  end

  def new
    @basket = Basket.new
    @basket.items.build
    @categorys =  Category.where(:income => false, :user_id => current_user.id, :active => true)
    respond_with(@basket, @item, @categorys)
  end

  def edit

  end

  def create

    @basket = Basket.new(basket_params)
    @basket.save
    respond_with(@basket)
  end

  def update
    @basket.update(basket_params)
    respond_with(@basket)
  end

  def destroy
    @basket.destroy
    respond_with(@basket)
  end

  private
    def set_basket
      @basket = Basket.find(params[:id])
    end

    def basket_params
      params.require(:basket).permit(:notice, :amount, :document, :user_id, :payment_id, :vendor_id, :purchase_date, items_attributes: [:id, :name, :price, :quantity, :notice, :category_id, :launch, :income, :user_id, :_destroy])
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/income_helper.rb
module IncomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/landing_helper.rb
module LandingHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/passthrough_helper.rb
module PassthroughHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
  def find_baskets_in_month(vendor_id)
    Basket.where(:user_id => current_user.id, :vendor_id => vendor_id )
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/baskets/_form.html.erb
<!-- Artikel hinzufügen angular -->
<div class="col-xs-12">
  <div class="panel panel-default" >
    <div class="panel-heading">
      <h3 class="panel-title">Artikel hinzufügen</h3>
    </div>

    <div class="panel-body">
      <input hidden ng-model="income" value="false"></input>
      <input hidden ng-model="launch" value="<%=@getPurchaseDate%>"></input>
      <input hidden ng-model="user_id" value="<%= current_user.id %>"></input>

      <div class="col-xs-12">
        <div class="form-group">
          <label class="" for="">Name</label>
          <div class="input-group">
            <div class="input-group-addon"><i class="fa fa-file-text"></i></div>
            <input ng-model="name" placeholder="Name" class="form-control"></input>
          </div>
        </div>
      </div>

      <div class="col-xs-6">
        <div class="form-group">
          <label class="" for="">Preis und Menge</label>
          <div class="input-group">
            <div class="input-group-addon"><i class="fa fa-euro"></i></div>
            <input type="number" step="any" ng-model="price" placeholder="Preis" class="form-control"></input>
            <input type="number" ng-model="quantity" placeholder="Menge" class="form-control"></input>
          </div>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="form-group">
          <label class="" for="">Kategorie</label>
          <div class="input-group">
            <select class="selectpicker"  ng-model="category">
            <% Category.where(:income => false, :user_id => current_user.id, :active => true).each do |category| %>
               <option value="<%= category.id %>" ><%= category.name %></option>
              <% end %>
            </select>
          </div>
        </div>
      </div>

      <div class="col-xs-12">
        <div class="form-group">
          <label class="" for="">Notiz</label>
          <div class="input-group form-inline">
            <div class="input-group-addon"><i class="fa fa-file-text"></i></div>
            <textarea ng-model="notice" class="form-control" placeholder="Notiz" ng-disabled="!hasNotice"></textarea>
            <div class="input-group-addon">
              <div class="checkbox">
                <label>
                  <input ng-model="hasNotice" type="checkbox" aria-label="Notiz">
                </label>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="panel-footer">
      <button ng-click="add($index)" class="btn btn-default">Hinzufügen</button>
    </div>
  </div>
</div>



<div class="col-xs-12">
  <%= form_for(@basket) do |f| %>

      <% if @basket.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@basket.errors.count, "error") %> prohibited this basket from being saved:</h2>

            <ul>
              <% @basket.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>



    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Anlegen</h3>
        </div>
        <div class="panel-body">
          <div class="col-xs-6">
            <div class="form-group">
              <label class="" for="">Händler: </label>
              <div class="input-group">
                  <%= f.collection_select(:vendor_id, Vendor.where(:user_id => current_user.id), :id, :name, {multiple: false}, :class=>'selectpicker')%>
              </div>
            </div>
          </div>


          <div class="col-xs-6">
            <div class="form-group">
              <label class="" for="">Einkaufsdatum:</label>
              <div class="input-group date">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <%= f.text_field :purchase_date, :value => Time.now.strftime("%d-%m-%Y"), :data => {:provide => "datepicker"}, :class => "form-control"%>

              </div>
            </div>
          </div>


          <!-- Tabelle der Anzulegenden Items -->
            <div class="col-xs-12">
                <div class="table table-hover">
                    <label class="" for="">Artikel:</label>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Anzahl</th>
                                <th>Preis</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="item in items">
                                <td>
                                    <input id="basket_items_attributes_{{item.id}}_name bianame" name="basket[items_attributes][{{item.id}}][name]" value="{{ item.name }}" type="text"></input>
                                </td>
                                <td>
                                    <input id="basket_items_attributes_{{item.id}}_quantity biaquantity" name="basket[items_attributes][{{item.id}}][quantity]" value="{{ item.quantity }}" type="text"></input>
                                </td>
                                <td>
                                    <input id="basket_items_attributes_{{item.id}}_price" name="basket[items_attributes][{{item.id}}][price]" value="{{ item.price }}" type="text"></input>
                                </td>
                                <td>
                                    <button class="btn btn-default" ng-click="rem($index)" data-toggle="tooltip" data-placement="bottom" title="Artikel löschen"><i class="fa fa-times"> </i></button>
                                </td>
                                  <td>
                                    <input id="basket_items_attributes_{{item.id}}_notice" name="basket[items_attributes][{{item.id}}][notice]" value="{{ item.notice }}" type="hidden"></input>
                                  </td>
                                  <td>
                                    <input id="basket_items_attributes_{{item.id}}_category_id" name="basket[items_attributes][{{item.id}}][category_id]" value="{{ item.category }}" type="hidden"></input>
                                  </td>
                                  <td>
                                    <input id="basket_items_attributes_{{item.id}}_income" name="basket[items_attributes][{{item.id}}][income]" value="false" type="hidden"></input>
                                  </td>
                                  <td>
                                    <input id="basket_items_attributes_{{item.id}}_launch" name="basket[items_attributes][{{item.id}}][launch]" type="hidden" value=""></input>
                                  </td>
                                  <td>
                                    <input id="basket_items_attributes_{{item.id}}_user_id" name="basket[items_attributes][{{item.id}}][user_id]" value="<%=current_user.id%>" type="hidden"></input>
                                  </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="panel-footer">
          <!-- Button trigger modal -->
          <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
            <i class="fa fa-save"></i> Anlegen
          </button>
        </div>

    </div><!--/.panel panel-default-->

</div><!--/.col-xs-12-->








    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Ausgabe bestätigen</h4>
          </div>

          <div class="modal-body">

            <div class="table table-hover">
              <caption><h3>Artikel Liste</h3></caption>
              <table class="table">
                <thead>
                <tr>
                  <th>Name</th>
                  <th>Anzahl</th>
                  <th>Preis</th>
                  <th></th>
                </tr>
                </thead>
                <tbody>
                <tr ng-repeat="item in items">
                  <td>
                    {{item.name}}
                  </td>
                  <td>
                    {{item.quantity}}
                  </td>
                  <td>
                    {{item.price}} &euro;
                  </td>
                  <td>
                    <button type="button" class="btn btn-default" ng-click="rem($index)" data-toggle="tooltip" data-placement="bottom" title="Artikel löschen"><i class="fa fa-times" ></i></button>
                  </td>
                </tr>
                <tr>
                  <td colspan="2"><strong>Summe</strong></td>
                  <td><strong>{{sum}} &euro;</strong></td>
                  <td></td>
                </tr>
                </tbody>
              </table>
            </div>


            <div class="col-xs-6">
              <div class="form-group">
                <label class="" for="">Zahlungsmethode</label>
                <div class="input-group">
                  <%= f.collection_select(:payment_id, Payment.where(:user_id => current_user.id, :active => true), :id, :name, {multiple: false}, :class=>'selectpicker')%>
                </div>
              </div>
            </div>


            <div class="col-xs-6">
              <div class="form-group">
                <label class="" for="">Summe der Ausgaben</label>
                <div class="input-group">
                  <div class="input-group-addon"><i class="fa fa-money"></i></div>
                  <%= f.number_field :amount, :class =>"form-control", :placeholder => "Summe der Ausgabe", :step =>'any', :value => "{{sum}}"%>
                </div>
              </div>
            </div>


            <div class="col-xs-12">
              <div class="form-group">
                <label class="" for="">Notiz</label>
                <div class="input-group">
                  <div class="input-group-addon"><i class="fa fa-file-text"></i></div>
                  <%= f.text_area :notice, :class =>"form-control", :placeholder => "Notiz"%>
                </div>
              </div>
            </div>



              <!-- Moritz Form für Dateiupload -->
              <div class="field">
                <%= f.label :document %><br>
                <%= f.file_field :document %>
              </div>

          </div>

          <div class="modal-footer">
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Speichern" , :class => "btn btn-default" %>
          </div>

        </div>
      </div>
    </div>
<% end %>

app/views/baskets/_form_edit.html.erb
<%= form_for(@basket) do |f| %>
  <% if @basket.errors.any? %>
    <div id="error_explanation" class="alert fade in alert-danger">
      <h3><%= pluralize(@basket.errors.count, "Fehler") %> beim anlegen einer Ausgabe:</h3>

      <ul>
      <% @basket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Einkauf abändern</h3>
    <p id="notice"><%= notice %></p>
  </div>

  <div class="panel-body">
    <div class="col-xs-6">
      <div class="form-group">
        <label class="" for="">Händler: </label>
        <div class="input-group">
          <select class="selectpicker" data-live-search="true">
            <% Vendor.where(:user_id => current_user.id).each do |vendor| %>
                <option> <%= vendor.name %> </option>
            <% end %>
          </select>
        </div>
      </div>
    </div>

    <div class="col-xs-6">
      <div class="form-group">
        <label class="" for="">Einkaufsdatum: </label>
        <div class="input-group">
          <%= f.text_field :purchase_date, :value => Time.now.to_s(:db), :data => {:provide => "datepicker"} %>
        </div>
      </div>
    </div>


      <div class="col-xs-12">
        <div class="tables tables-hover">
          <label class="" for="">Artikel:</label>
          <table class="table">
            <thead>
            <tr>
              <th>Name</th>
              <th>Preis</th>
              <th>Menge</th>
              <th>Notiz</th>
              <th>Kategorie</th>
              <th>Löschen</th>
            </tr>
            </thead>
            <tbody>
            <%= f.fields_for :items do |items_form| %>
                <tr>
                  <%= items_form.hidden_field :id %>
                  <td><%= items_form.text_field :name %></td>
                  <td><%= items_form.number_field :price, :step => 'any' , :class => "columnbasket" %></td>
                  <td><%= items_form.number_field :quantity, :min => 1 ,:class => "columnbasket"%></td>
                  <td><%= items_form.text_field :notice ,:class => "columnbasket" %></td>
                  <td><%= items_form.collection_select :category_id, Category.where(:income => false, :active => true, :user_id => current_user.id), :id, :name, multiple: false %></td>
                  <td><%= items_form.check_box :_destroy %></td>
                </tr>
            <% end %>
            </tbody>
          </table>


        </div>


      </div>

      <div class="col-xs-6">
          <div class="form-group">
                <label class="" for="">Dokument:</label>
                <div class="foto_enlarge">
                  <%= image_tag @basket.document.url(:normal), :class => "thumbnail" if @basket.document? %>
                </div>
                  <div class="field">
                  <%= f.file_field :document, :class =>"form-control btn-file" %>
                </div>
          </div>
      </div>



      <div class="col-xs-6">
        <div class="form-group">
            <label class="" for="">Summe:</label>
            <%= f.number_field :amount ,:class =>"form-control", :step => 'any' %>
        </div>
      </div>


    <div class="col-xs-6">
      <div class="form-group">
        <label class="" for="">Zahlungsmethode: </label>
        <div class="input-group">
          <select class="selectpicker" data-live-search="true">
            <% Payment.where(:user_id => current_user.id, :active => true).each do |payment| %>
                <option <%= "selected" if payment.id == @basket.payment_id %> value="<%= payment.id %>"><%= payment.name %></option>
            <% end %>
          </select>
        </div>
      </div>
    </div>


      <div class="col-xs-12">
        <div class="form-group">
            <label class="" for="">Notiz:</label>
            <%= f.text_field :notice ,:class =>"form-control" %>
        </div>
      </div>

  </div>

  <div class="panel-footer">
      <%= f.submit "Speichern" , :class => "btn btn-default" %>
  </div>

</div>


    <div class="field">
      <%= f.hidden_field :user_id, :value => current_user.id %>
    </div>



<% end %>

app/views/baskets/edit.html.erb
<div class="page-header">

  <h1> <%= link_to baskets_path do %>  <i class="fa fa-arrow-left"></i> <% end %>Ausgabe ändern<i class="fa fa-building-o pull-right"></i> </h1>

</div>

<div class="col-lg-12">
  <%= render 'form_edit' %>
</div>

app/views/baskets/index.html.erb
<div class="page-header">
  <div class="text-center">
    <h1>

        Ausgaben
      <i class="fa fa-building-o pull-right"></i>
    </h1>
  </div>
</div>
<div role="tabpanel">
  <%= link_to '+ Hinzufügen', new_basket_path, :class => 'btn btn-success pull-left', :role => 'button' %>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" >
      <a href="#grid" aria-controls="grid" role="tab" data-toggle="tab">
        <i class="fa fa-th"></i> Grid
      </a>
    </li>
    <li role="presentation" class="active">
      <a href="#list" aria-controls="list" role="tab" data-toggle="tab">
        <i class="fa fa-bars"></i> List
      </a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <br>
    <div role="tabpanel" class="tab-pane fade " id="grid">
        <% @baskets.each do |basket| %>
            <div class="col-xs-6 col-lg-4">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <%= link_to basket do %><h3 class="panel-title text-center"><i class="fa fa-calendar pull-left"></i> <%= basket.purchase_date.strftime("%d/%m/%Y")  %></h3><% end %>
                </div>
                <div class="panel-body">

                  <div class="text-center">
                    <h4 data-toggle="tooltip" data-placement="bottom" title="Summe der Artikel"> <%= basket.amount %> <i class="fa fa-euro"></i></h4>
                  </div>
                  <hr>
                  <p><i class="fa fa-building-o"></i> <small><%= show_vendor_name(basket.vendor_id) %></small></p>
                  <p><i class="fa fa-credit-card"></i> <small><%= show_payment_name(basket.payment_id) %></small></p>

                  <button type="button" class="btn btn-default btn-xs btn-block popover-top" data-toggle="popover" title="Notiz" data-content="<%= basket.notice %>"><i class="fa fa-file-text"></i>  Notiz </button>

                </div>
                <div class="panel-footer">
                  <%= link_to edit_basket_path(basket) do %>  <button class="btn btn-default"> <i class="fa fa-pencil-square-o"></i> Ändern </button> <% end %>
                  <%= link_to basket, method: :delete, data: { confirm: 'Wollen Sie den Warenkorb löschen?' } do %> <button class="btn btn-default"> <i class="fa fa-trash-o"></i> Löschen </button>  <% end %>
                </div>
              </div>
            </div>
        <% end %>
    </div>

    <div role="tabpanel" class="tab-pane fade active in" id="list">
      <div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Entwicklung der Ausgaben im aktuellen Jahr</h3>
          </div>
          <div class="panel-body">
            <%= high_chart("my_id10", @chartBaskets)  %>
          </div>
        </div>


      <div class="list-group">
        <% @baskets.each do |basket| %>
            <%= link_to basket_path(basket) do %>
                <li class="list-group-item">
                  <%= basket.purchase_date.strftime("%d/%m/%Y") %>
                  <span class="badge pull-right"> <%= basket.amount %> &euro;</span>
                </li>
            <% end %>
        <% end %>
      </div>
    </div>

  </div>
</div>

</div>

<%= link_to '+', new_basket_path, :class => 'btn btn-default', :role => 'button' %>

app/views/baskets/new.html.erb
<div class="page-header">

  <h1> <%= link_to baskets_path do %>  <i class="fa fa-arrow-left"></i> <% end %>Ausgabe<i class="fa fa-building-o pull-right"></i> </h1>

</div>

<div class="col-lg-12" ng-controller="ItemController">
  <%= render 'form' %>
</div>

app/views/baskets/show.html.erb
<div class="page-header">

      <h1> <%= link_to baskets_path do %>  <i class="fa fa-arrow-left"></i> <% end %> Ausgabe Details <i class="fa fa-building-o pull-right"></i> </h1>

</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Einkauf vom <%= @basket.purchase_date.strftime("%d.%m.%Y") %> </h3>


  </div>

  <div class="panel-body">

    <div class="col-xs-12">
      <div class="tables tables-hover">
        <label class="" for="">Artikel:</label>
        <table class="table table-condensed">
          <thead>
          <tr>
            <th>Name</th>
            <th>Preis</th>
            <th>Anzahl</th>
            <th>Notiz</th>
            <th>Kategorie</th>
          </tr>
          </thead>
          <tbody>
          <% find_items_of_basket(@basket).each do |item| %>
              <tr>
                <td><%= item.name %></td>
                <td><%= item.price %> &euro;</td>
                <td><%= item.quantity %></td>
                <td><%= item.notice %></td>
                <td><%= show_category_name(item.category_id) %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-6">
      <div class="form-group">
        <label class="" for="">Dokument:</label>
        <div class="foto_enlarge">
            <%= image_tag @basket.document.url(:normal), :class => "thumbnail" if @basket.document? %>
        </div>
      </div>
    </div>

    <div class="col-xs-6">
      <div class="form-group">
        <label class="" for="">Händler:</label>
        <input id="vendor_id" class="form-control" type="text" value="<%= show_vendor_name(@basket.vendor_id) %>" placeholder="<%= show_vendor_name(@basket.vendor_id) %>" disabled="disabled">
      </div>
    </div>


    <div class="col-xs-6">
      <div class="form-group">
        <label class="" for="">Summe:</label>
        <input id="amount" class="form-control" type="text" value="<%= @basket.amount %> &euro;" placeholder="<%= @basket.amount %>" disabled="disabled">
      </div>
    </div>

    <div class="col-xs-6">
      <div class="form-group">
        <label class="" for="">Zahlungsmethode:</label>
        <input id="amount" class="form-control" type="text" value="<%= show_payment_name(@basket.payment_id) %>" placeholder="<%= show_payment_name(@basket.payment_id) %>" disabled="disabled">
      </div>
    </div>

    <div class="col-xs-12">
      <div class="form-group">
        <label class="" for="">Notiz:</label>
        <input id="notice" class="form-control" type="text" value="<%= @basket.notice %>" placeholder="<%= @basket.notice %>" disabled="disabled">
      </div>
    </div>
  </div>

  <div class="panel-footer">
    <%= link_to baskets_path do %> <button class="btn btn-default btn-xs"> <i class="fa fa-arrow-left"></i> Zurück </button> <% end %>
    <%= link_to edit_basket_path(@basket) do %> <button class="btn btn-default btn-xs"> <i class="fa fa-pencil-square-o"></i> Ändern </button> <% end %>
  </div>


</div>