config/routes.rb
Rails.application.routes.draw do

  get 'passthrough/index'

  get 'income/new', to: 'income#new'
  get 'income/show', to: 'income#show'
  get 'income/edit', to: 'income#edit'
  get 'incomes/', to: 'income#index'

  resources :categories
  resources :payments
  resources :accounts
  resources :articles
  resources :items
  resources :vendors
  resources :baskets
  resources :income

  get 'welcome/index'
  get 'landing/index'
  get 'landing/help'

  devise_for :users

  root 'passthrough#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  has_many :payments
  validates :number, :bic, :name, :user_id, presence: true

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  has_many :items
  validates :name, :price, :active, presence: true
  validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }
end

app/models/basket.rb
class Basket < ActiveRecord::Base
  belongs_to :user
  belongs_to :payment
  belongs_to :vendor
  has_many :items, :dependent => :destroy
  accepts_nested_attributes_for :items, :allow_destroy => true
  validates :amount, :user_id, :vendor_id, :purchase_date, :payment_id, presence: true
  validates :amount, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }

  mount_uploader :document, DocumentUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  belongs_to :glyphicon
  validates :name, :user_id, presence: true
end

app/models/glyphicon.rb
class Glyphicon < ActiveRecord::Base
  has_many :categories
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :basket
  belongs_to :category
  belongs_to :article
  belongs_to :user
  validates :name, presence: true
  validates :category_id, :user_id, :price,  presence: true
  validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
  has_many :basket
  validates :name, :bic, :number, :user_id, presence: true
end

app/models/period.rb
class Period < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :baskets
  has_many :categories
  has_many :payments
  has_many :items
  has_many :vendors
  #attr_accessor :email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:email]
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'


end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_many :baskets
  belongs_to :user
  validates :name, :user_id, presence: true


  mount_uploader :logo, DocumentUploader


end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html

  def index
    @vendors = Vendor.where(:user_id => current_user.id)

    vendor_name = []
    vendor_amount = []
    @vendors.each do |v|
      vendor_name << v.name
      vendor_amount << sum_amount(find_baskets_of_vendor(v.id))
    end

    @chartVendor = LazyHighCharts::HighChart.new('bar') do |f|
      f.series(:name=> 'Betrag', :showInLegend => false, :data=> vendor_amount)
      f.options[:chart][:defaultSeriesType] = "bar"
      f.options[:xAxis] = {:plot_bands => "none", :title=>{:text=>"Kategorien"}, :categories => vendor_name}
      f.options[:yAxis][:title] = {:text=>"Euro"}
      f.options[:chart][:backgroundColor] = 'rgba(0, 0, 0, 0)'
    end

    respond_with(@vendors)
  end

  def show
    @filteredBaskets = Basket.where(:vendor_id => @vendor.id, :user_id => current_user.id)
    respond_with(@vendor, @filteredBaskets)
  end

  def new
    @vendor = Vendor.new
    respond_with(@vendor)
  end

  def edit
  end

  def create
    @vendor = Vendor.new(vendor_params)
    @vendor.save
    respond_with(@vendor)
  end

  def update
    # Logo-Deletion, only Logolink = null, filedelete not implemented
    if vendor_params[:remove_logo] == "1"
      @logo = vendor_params[:logo]
      @logo.nil?

    end
    @vendor.update(vendor_params)
    respond_with(@vendor)
  end

  def destroy
    @vendor.destroy
    respond_with(@vendor)
  end

  private
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    def vendor_params
      params.require(:vendor).permit(:name, :logo, :remove_logo, :user_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/income_helper.rb
module IncomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/landing_helper.rb
module LandingHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/passthrough_helper.rb
module PassthroughHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
  def find_baskets_in_month(vendor_id)
    Basket.where(:user_id => current_user.id, :vendor_id => vendor_id )
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/vendors/_form.html.erb
<%= form_for(@vendor, :html => {:multipart => true}) do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation" class="alert fade in alert-danger">
      <h3><%= pluralize(@vendor.errors.count, "Fehler") %> beim anlegen eines Händlers:</h3>

      <ul>
      <% @vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Anlegen</h3>
  </div>
  <div class="panel-body">
    <%= f.hidden_field :user_id, :value => current_user.id %>

    <div class="col-xs-6">
      <div class="form-group">
        <label>Name:</label>
        <div class="input-group">
          <div class="input-group-addon"><i class="fa fa-file-text"></i></div>
          <%= f.text_field :name, :class =>"form-control", :placeholder => "Name" %>
        </div>
      </div>
    </div>

    <div class="col-xs-6">

    </div>


      <div class="col-xs-12">
        <div class="form-group">
          <label>Logo upload:</label>
          
          <%= f.file_field :logo, :class =>"form-control btn-file", :placeholder => "Logo" %>
        </div>
      </div>







  </div>

<div class="panel-footer">
  <%= f.submit "Neu Anlegen" , :class => "btn btn-default" %>
</div>




</div>
<% end %>

app/views/vendors/_form_edit.html.erb
<%= form_for(@vendor, :html => {:multipart => true}) do |f| %>
    <% if @vendor.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

          <ul>
            <% @vendor.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Ändern</h3>
      </div>
      <div class="panel-body">
        <%= f.hidden_field :user_id, :value => current_user.id %>

        <div class="col-xs-6">
          <div class="form-group">
            <label>Name:</label>


            <%= f.text_field :name, :class =>"form-control", :placeholder => "Name" %>
          </div>
        </div>

        <div class="col-xs-6">
          <label>Logo:</label>
          <%= image_tag @vendor.logo.url(:normal) if @vendor.logo? %>
        </div>


        <div class="col-xs-12">
          <div class="form-group">
            <label>Logo upload:</label>
            <%= f.file_field :logo, :class =>"form-control btn btn-default btn-file", :placeholder => "Logo" %>
          </div>
        </div>

        <div class="col-xs-6">
          <label>Logo Löschen:</label>
          <%= f.check_box :remove_logo %>
        </div>

      </div>

      <div class="panel-footer">
        <%= f.submit "Speichern" , :class => "btn btn-default" %>
      </div>

    </div>
<% end %>

app/views/vendors/_list.html.erb
<div class="list-group">
  <% Vendor.where(:user_id => current_user.id).each do |vendor| %>
      <%= link_to vendor_path(vendor) do %>
          <li class="list-group-item">
          <%= vendor.name %>
          <span class="badge pull-right"> <%=sum_price(find_items_of_basket(find_baskets_of_vendor(vendor.id))) %> &euro;</span>
          </li>
      <% end %>
  <% end %>
</div>

app/views/vendors/edit.html.erb
<div class="page-header">

  <h1> <%= link_to vendors_path do %>  <i class="fa fa-arrow-left"></i> <% end %>Händler<i class="fa fa-building-o pull-right"></i></h1>

</div>

<%= render 'form_edit' %>

app/views/vendors/index.html.erb
<div class="page-header">
  <div class="text-center">
    <h1>
      Händler
      <i class="fa fa-building-o pull-right"></i>
    </h1>
  </div>
</div>

<div role="tabpanel">
  <%= link_to '+ Hinzufügen', new_vendor_path, :class => 'btn btn-success pull-left', :role => 'button' %>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" >
        <a href="#grid" aria-controls="grid" role="tab" data-toggle="tab">
            <i class="fa fa-th"></i> Grid
        </a>
    </li>
    <li role="presentation" class="active">
        <a href="#list" aria-controls="list" role="tab" data-toggle="tab">
            <i class="fa fa-bars"></i> List
        </a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <br>
    <div role="tabpanel" class="tab-pane fade" id="grid">
      <% @vendors.each do |vendor| %>
          <div class="col-xs-6 col-lg-4">
            <div class="panel panel-default">
              <div class="panel-heading clearfix" style="height:88px">
                    <%= link_to vendor do%>
                        <h3 class="panel-title " ><%= vendor.name %></h3>

                    <% end %>

              </div>
              <div class="panel-body">
                <div class="text-center">
                  <h4 data-toggle="tooltip" data-placement="bottom" title="Summe der bisherigen Ausgaben beim Händler">  <%= sum_amount(find_baskets_of_vendor(vendor.id)) %> <i class="fa fa-euro"></i></h4>
                </div>
                <hr>
                <div class="text-center" style="height:50px">
                  <% if vendor.logo? %>
                      <%= image_tag vendor.logo.url(:thumb), :class => 'img-thumbnail hidden-xs hidden-sm'%>
                  <% else %>
                      <img src="/no_pic.png">
                  <% end %>

                </div>


              </div>
              <div class="panel-footer">
                <%= link_to edit_vendor_path(vendor) do %>  <button class="btn btn-default"> <i class="fa fa-pencil-square-o"></i> Ändern </button> <% end %>
                <%= link_to vendor, method: :delete, data: { confirm: 'Wollen Sie den Händler löschen?' } do %> <button class="btn btn-default"> <i class="fa fa-trash-o"></i> Löschen </button>  <% end %>
              </div>
            </div>
          </div>
      <% end %>
    </div>


    <div role="tabpanel" class="tab-pane fade active in" id="list">
            <div class="col-lg-12">
              <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Übersicht</h3>
                </div>
                <div class="panel-body">
                    <%= high_chart("my_id6", @chartVendor)  %>
                </div>
          </div>


          <div class="list-group">
            <% Vendor.where(:user_id => current_user.id).each do |vendor| %>
                <%= link_to vendor_path(vendor) do %>
                    <li class="list-group-item">
                      <%= vendor.name %>
                      <span class="badge pull-right"> <%= sum_amount(find_baskets_of_vendor(vendor.id)) %> &euro;</span>
                    </li>
                <% end %>
            <% end %>
          </div>
    </div>



  </div>
</div>


<%= link_to '+', new_vendor_path, :class => 'btn btn-default pull-left', :role => 'button' %>
</div>

app/views/vendors/new.html.erb
<div class="page-header">

  <h1> <%= link_to vendors_path do %>  <i class="fa fa-arrow-left"></i> <% end %>Händler<i class="fa fa-building-o pull-right"></i></h1>

</div>


<div class="col-sm-12 col-md-7">
  <%= render 'form' %>
</div>




<div class="col-md-5 hidden-sm hidden-xs">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Erstellt</h3>
    </div>
    <div class="panel-body">
  <%= render 'list' %>
    </div>
  </div>
</div>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">

  <h1> <%= link_to vendors_path do %>  <i class="fa fa-arrow-left"></i> <% end %> Händler Details <i class="fa fa-building-o pull-right"></i></h1>
</div>

<div class="col-xs-12">
  <div class="panel panel-default">
      <div class="panel-heading">
            <h3 class="panel-title text-center">
              <%= @vendor.name %>
            </h3>
      </div>
      <div class="panel-body">
        <%= image_tag @vendor.logo.url(:normal) if @vendor.logo? %>
        <div class="table">
          <table class="table table-hover">
            <thead>
            <tr>
              <th>Datum</th>
              <th>Notiz</th>
              <th>Preis</th>
            </tr>
            </thead>
            <tbody>
            <% @filteredBaskets.each do |basket| %>
                <tr onclick="location.href='/baskets/<%= basket.id %>'">
                  <td><%= basket.created_at %></td>
                  <td><%= basket.notice %> </td>
                  <td><%= basket.amount %> &euro;</td>
                </tr>
            <% end %>
            <tr>
              <td colspan="2"><strong>Summe:</strong></td>
              <td> <%= sum_amount(@filteredBaskets)  %> &euro; </td>
            </tr>
            </tbody>
          </table>
        </div>

      </div>
      <div class="panel-footer">
        <%= link_to vendors_path do %>  <button class="btn btn-default btn-xs"> <i class="fa fa-arrow-left"></i> Zurück </button> <% end %>
        <%= link_to edit_vendor_path(@vendor) do %>  <button class="btn btn-default btn-xs"> <i class="fa fa-pencil-square-o"></i> Ändern </button> <% end %>
      </div>
  </div>
</div>