config/routes.rb
Rails.application.routes.draw do

  get 'passthrough/index'

  get 'income/new', to: 'income#new'
  get 'income/show', to: 'income#show'
  get 'income/edit', to: 'income#edit'
  get 'incomes/', to: 'income#index'

  resources :categories
  resources :payments
  resources :accounts
  resources :articles
  resources :items
  resources :vendors
  resources :baskets
  resources :income

  get 'welcome/index'
  get 'landing/index'
  get 'landing/help'

  devise_for :users

  root 'passthrough#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  has_many :payments
  validates :number, :bic, :name, :user_id, presence: true

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  has_many :items
  validates :name, :price, :active, presence: true
  validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }
end

app/models/basket.rb
class Basket < ActiveRecord::Base
  belongs_to :user
  belongs_to :payment
  belongs_to :vendor
  has_many :items, :dependent => :destroy
  accepts_nested_attributes_for :items, :allow_destroy => true
  validates :amount, :user_id, :vendor_id, :purchase_date, :payment_id, presence: true
  validates :amount, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }

  mount_uploader :document, DocumentUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  belongs_to :glyphicon
  validates :name, :user_id, presence: true
end

app/models/glyphicon.rb
class Glyphicon < ActiveRecord::Base
  has_many :categories
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :basket
  belongs_to :category
  belongs_to :article
  belongs_to :user
  validates :name, presence: true
  validates :category_id, :user_id, :price,  presence: true
  validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
  has_many :basket
  validates :name, :bic, :number, :user_id, presence: true
end

app/models/period.rb
class Period < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :baskets
  has_many :categories
  has_many :payments
  has_many :items
  has_many :vendors
  #attr_accessor :email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:email]
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'


end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_many :baskets
  belongs_to :user
  validates :name, :user_id, presence: true


  mount_uploader :logo, DocumentUploader


end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html

  def index
    @payments = Payment.where(:user_id => current_user.id)

    payment_name = []
    payment_amount = []
    @payments.each do |p|
      payment_name << p.name
      payment_amount << sum_amount(find_baskets_of_payment(p.id))
    end

    @chartPaymentsAmount = LazyHighCharts::HighChart.new('pie') do |f|
      f.chart({:defaultSeriesType=>"pie"} )
      series = {
          :type=> 'pie',
          :showInLegend => false,
          :data=> [
          [payment_name[0], payment_amount[0]],
          [ payment_name[1], payment_amount[1]],
          [ payment_name[2], payment_amount[2]],
          [ payment_name[3], payment_amount[3]]
          ]
      }
      f.series(series)
      f.options[:title][:text] = 'Wertmäßiger Anteil'
      f.options[:chart][:backgroundColor] = 'rgba(0, 0, 0, 0)'
      f.legend(:layout=> 'vertical',:style=> {:left=> 'auto', :bottom=> 'auto',:right=> 'auto',:top=> 'auto'})
      f.plot_options(:pie=>{
                         :allowPointSelect=>true,
                         :cursor=>"pointer" ,
                         :dataLabels=>{
                             :enabled=>true,
                             :color=>"black",
                             :style=>{
                                 :font=>"13px Trebuchet MS, Verdana, sans-serif"
                             }
                         }
                     })
    end


    @chartPaymentsCount = LazyHighCharts::HighChart.new('pie') do |f|
      f.chart({:defaultSeriesType=>"pie" } )
      series = {
          :type=> 'pie',
          :showInLegend => false,
          :data=> [
              [ payment_name[0], Basket.where(:user_id => current_user.id, :payment_id => Payment.where(:user_id => current_user.id, :name => payment_name[0]).pluck(:id)).count],
              [ payment_name[1], Basket.where(:user_id => current_user.id, :payment_id => Payment.where(:user_id => current_user.id, :name => payment_name[1]).pluck(:id)).count],
              [ payment_name[2], Basket.where(:user_id => current_user.id, :payment_id => Payment.where(:user_id => current_user.id, :name => payment_name[2]).pluck(:id)).count],
              [ payment_name[3], Basket.where(:user_id => current_user.id, :payment_id => Payment.where(:user_id => current_user.id, :name => payment_name[3]).pluck(:id)).count]
          ]
      }
      f.series(series)
      f.options[:title][:text] = 'Anzahl der Bezahlvorgänge'
      f.options[:chart][:backgroundColor] = 'rgba(0, 0, 0, 0)'
      f.legend(:layout=> 'vertical',:style=> {:left=> 'auto', :bottom=> 'auto',:right=> 'auto',:top=> 'auto'})
      f.plot_options(:pie=>{
                         :allowPointSelect=>true,
                         :cursor=>"pointer" ,
                         :dataLabels=>{
                             :enabled=>true,
                             :color=>"black",
                             :style=>{
                                 :font=>"13px Trebuchet MS, Verdana, sans-serif"
                             }
                         }
                     })
    end

    respond_with(@payments)
  end

  def show
    respond_with(@payment)
  end

  def new
    @payment = Payment.new
    respond_with(@payment)
  end

  def edit
  end

  def create
    @payment = Payment.new(payment_params)
    @payment.save
    respond_with(@payment)
  end

  def update
    @payment.update(payment_params)
    respond_with(@payment)
  end

  def destroy
    @payment.destroy
    respond_with(@payment)
  end

  private
    def set_payment
      @payment = Payment.find(params[:id])
    end

    def payment_params
      params.require(:payment).permit(:user_id, :number, :bic, :active, :name)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/income_helper.rb
module IncomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/landing_helper.rb
module LandingHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/passthrough_helper.rb
module PassthroughHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
  def find_baskets_in_month(vendor_id)
    Basket.where(:user_id => current_user.id, :vendor_id => vendor_id )
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation" class="alert fade in alert-danger">
      <h3><%= pluralize(@payment.errors.count, "Fehler") %> beim anlegen einer Zahlungsmethode:</h3>

      <ul>
      <% @payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="panel panel-default">


      <div class="panel-heading">
        <h3 class="panel-title">Anlegen</h3>
      </div>

      <div class="panel-body">

        <div class="col-xs-6">
          <%= f.check_box :active, :checked => true %>
          <%= f.label :active %><br>
          <%= f.hidden_field :user_id, :value => current_user.id %><br>
        </div>


        <div class="col-xs-12">
          <div class="form-group">
            <label class="" for="">Name:</label>
            <div class="input-group">
                <div class="input-group-addon"><i class="fa fa-file-text"></i></div>
                <%= f.text_field :name, :class =>"form-control", :placeholder => "Name" %>
            </div>
          </div>
        </div>

        <div class="col-xs-6">
          <div class="form-group">
            <label class="" for="">Nummer:</label>
            <div class="input-group">
              <div class="input-group-addon"><i class="fa fa-university"></i></div>
              <%= f.text_field :number, :class =>"form-control", :placeholder => "BIC" %>
            </div>
          </div>
        </div>

        <div class="col-xs-6">
          <div class="form-group">
            <label class="" for="">BIC:</label>
            <div class="input-group">
              <div class="input-group-addon"><i class="fa fa-university"></i></div>
              <%= f.text_field :bic, :class =>"form-control", :placeholder => "BIC" %>
            </div>

          </div>
        </div>

      </div>

      <div class="panel-footer">
        <%= f.submit "Speichern" , :class => "btn btn-default" %>
      </div>
    </div>
<% end %>

app/views/payments/_list.html.erb
<div class="list-group">
  <% Payment.where(:user_id => current_user.id).each do |payment| %>
      <%= link_to payment_path(payment) do %>
          <% if !payment.active? %>
              <li class="list-group-item">
          <% else %>
              <li class="list-group-item list-group-item-success">
          <% end %>
          <%= payment.name %>
          <span class="badge pull-right"> <%=sum_price(find_items_of_basket(find_baskets_of_payment(payment.id))) %> &euro;</span>
          </li>
      <% end %>
  <% end %>
</div>

app/views/payments/edit.html.erb
<div class="page-header">

  <h1> <%= link_to payments_path do %>  <i class="fa fa-arrow-left"></i> <% end %>Zahlungsmethode ändern<i class="fa fa-credit-card pull-right"></i></h1>

</div>
<%= render 'form' %>

app/views/payments/index.html.erb
<div class="page-header">
  <div class="text-center">
    <h1>
      Zahlungsmethoden
      <i class="fa fa-credit-card pull-right"></i>
    </h1>
  </div>
</div>

<div role="tabpanel">
  <%= link_to '+ Hinzufügen', new_payment_path, :class => 'btn btn-success pull-left', :role => 'button' %>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" >
      <a href="#grid" aria-controls="grid" role="tab" data-toggle="tab">
        <i class="fa fa-th"></i> Grid
      </a>
    </li>

    <li role="presentation" class="active">
      <a href="#list" aria-controls="list" role="tab" data-toggle="tab">
        <i class="fa fa-bars"></i> List
      </a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
      <br>
      <div role="tabpanel" class="tab-pane fade " id="grid">

      <% @payments.each do |payment| %>
          <div class="col-xs-6 col-lg-4">
            <% if (payment.active) %>
             <div class="panel panel-success">
            <% else %>
             <div class="panel panel-default">
            <% end %>
                <div class="panel-heading">
                  <%= link_to payment do %>
                      <h3 class="panel-title"><%= payment.name %>
                        <% if (payment.active) %>
                            <i class="fa fa-check pull-right" data-toggle="tooltip" data-placement="left" title="Account ist aktiv"></i>
                        <% else %>
                            <i class="fa fa-times pull-right" data-toggle="tooltip" data-placement="left" title="Account ist inaktiv"></i>
                        <% end %>
                      </h3>
                  <% end %>
                </div>
                <div class="panel-body">
                  <div class="text-center">
                    <h4 data-toggle="tooltip" data-placement="bottom" title="Summe der bisherigen Ausgaben beim Händler">  <%= sum_amount(find_baskets_of_payment(payment.id)) %> <i class="fa fa-euro"></i></h4>

                  </div>
                  <hr>

                  <p><i class="fa fa-university"></i> IBAN: <br>
                  <small><%= payment.number %></small> </p>
                  <p><i class="fa fa-university"></i> BIC: <br>
                  <small><%= payment.bic %></small></p>
                </div>

                <div class="panel-footer">
                  <%= link_to edit_payment_path(payment) do %>  <button class="btn btn-default"> <i class="fa fa-pencil-square-o"></i> Ändern </button> <% end %>
                  <%= link_to payment, method: :delete, data: { confirm: 'Wollen Sie die Zahlungsmethode löschen?' } do %> <button class="btn btn-default"> <i class="fa fa-trash-o"></i> Löschen </button>  <% end %>
                </div>
              </div>
            </div>
       <% end %>
      </div>

      <div role="tabpanel" class="tab-pane fade active in" id="list">
          <div class="col-lg-12">
              <div class="panel panel-default">

                <div class="panel-heading">
                  <h3 class="panel-title">Übersicht (4 Zahlungsmethoden)</h3>
                </div>

                <div class="panel-body">
                      <div class="col-lg-6" >
                      <%= high_chart("my_id7", @chartPaymentsAmount)  %>
                      </div>
                      <div class="col-lg-6">
                        <%= high_chart("my_id8", @chartPaymentsCount)  %>
                      </div>
                </div>
              </div>

              <div class="list-group">
                <%@payments.each do |payment| %>
                    <%= link_to payment_path(payment) do %>
                        <% if !payment.active? %>
                            <li class="list-group-item">
                        <% else %>
                            <li class="list-group-item list-group-item-success">
                        <% end %>
                        <%= payment.name %>
                        <span class="badge pull-right"> <%= sum_amount(find_baskets_of_payment(payment.id))  %> &euro;</span>
                            </li>
                    <% end %>
                <% end %>
              </div>
          </div>
      </div>

  </div>
</div>

<%= link_to '+', new_payment_path, :class => 'btn btn-default', :role => 'button' %>

app/views/payments/new.html.erb
<div class="page-header">

  <h1> <%= link_to payments_path do %>  <i class="fa fa-arrow-left"></i> <% end %>Zahlungsmethode<i class="fa fa-credit-card pull-right"></i></h1>

</div>


<div class="col-sm-12 col-md-7">
  <%= render 'form' %>
</div>




<div class="col-md-5 hidden-sm hidden-xs">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Liste</h3>
    </div>
    <div class="panel-body">
  <%= render 'list' %>
    </div>
  </div>
</div>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1> <%= link_to payments_path do %>  <i class="fa fa-arrow-left"></i> <% end %> Zahlungsmethoden Details <i class="fa fa-credit-card pull-right"></i></h1>
</div>

<div class="col-xs-12">


  <% if (@payment.active) %>
      <div class="panel panel-success">
  <% else %>
      <div class="panel panel-default">
  <% end %>


      <div class="panel-heading">
        <%= link_to @payment do %>
            <h3 class="panel-title text-center">
              <%= @payment.name %>
              <% if (@payment.active) %>
                  <i class="fa fa-check pull-right" data-toggle="tooltip" data-placement="left" title="Category ist aktiv"></i>
              <% else %>
                  <i class="fa fa-times pull-right" data-toggle="tooltip" data-placement="left" title="Category ist inaktiv"></i>
              <% end %>
            </h3>
        <% end %>
      </div>


      <div class="panel-body">
        <div class="col-xs-6"><caption><strong><i class="fa fa-university"></i> IBAN: <%= @payment.number %></strong></caption></div>
        <div class="col-xs-6"><strong><i class="fa fa-university"></i>  BIC: <%= @payment.bic %></strong></div>

        <div class="table col-xs-12">
          <table class="table table-hover">
            <thead>
            <tr>
              <th>Datum</th>
              <th>Notiz</th>
              <th>Preis</th>
            </tr>
            </thead>
            <tbody>
            <% find_baskets_of_payment(@payment.id).each do |basket| %>
                <tr onclick="location.href='/baskets/<%= basket.id %>'">
                  <td><%= basket.created_at %></td>
                  <td><%= basket.notice %> &euro;</td>
                  <td><%= basket.amount %></td>
                </tr>
            <% end %>
            <tr>
              <td colspan="2"><strong>Summe:</strong></td>
              <td> <%= sum_amount(find_baskets_of_payment(@payment.id))  %> &euro; </td>
            </tr>
            </tbody>
          </table>
        </div>

      </div>


      <div class="panel-footer">
        <%= link_to payments_path do %> <button class="btn btn-default btn-xs"> <i class="fa fa-arrow-left"></i> Zurück </button> <% end %>
        <%= link_to edit_payment_path(@payment) do %> <button class="btn btn-default btn-xs"> <i class="fa fa-pencil-square-o"></i> Ändern </button> <% end %>
      </div>


    </div>
</div>