config/routes.rb
Rails.application.routes.draw do

  get 'passthrough/index'

  get 'income/new', to: 'income#new'
  get 'income/show', to: 'income#show'
  get 'income/edit', to: 'income#edit'
  get 'incomes/', to: 'income#index'

  resources :categories
  resources :payments
  resources :accounts
  resources :articles
  resources :items
  resources :vendors
  resources :baskets
  resources :income

  get 'welcome/index'
  get 'landing/index'
  get 'landing/help'

  devise_for :users

  root 'passthrough#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  has_many :payments
  validates :number, :bic, :name, :user_id, presence: true

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  has_many :items
  validates :name, :price, :active, presence: true
  validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }
end

app/models/basket.rb
class Basket < ActiveRecord::Base
  belongs_to :user
  belongs_to :payment
  belongs_to :vendor
  has_many :items, :dependent => :destroy
  accepts_nested_attributes_for :items, :allow_destroy => true
  validates :amount, :user_id, :vendor_id, :purchase_date, :payment_id, presence: true
  validates :amount, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }

  mount_uploader :document, DocumentUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  belongs_to :glyphicon
  validates :name, :user_id, presence: true
end

app/models/glyphicon.rb
class Glyphicon < ActiveRecord::Base
  has_many :categories
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :basket
  belongs_to :category
  belongs_to :article
  belongs_to :user
  validates :name, presence: true
  validates :category_id, :user_id, :price,  presence: true
  validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
  has_many :basket
  validates :name, :bic, :number, :user_id, presence: true
end

app/models/period.rb
class Period < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :baskets
  has_many :categories
  has_many :payments
  has_many :items
  has_many :vendors
  #attr_accessor :email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:email]
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'


end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_many :baskets
  belongs_to :user
  validates :name, :user_id, presence: true


  mount_uploader :logo, DocumentUploader


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html

  def index
    @categories = Category.where(:user_id => current_user.id).order(active: :desc, income: :desc)
    category_name = []
    category_amount = []
    @categories.each do |c|
      category_name << c.name
      category_amount << (sum_price(find_income_items_of_category(c.id)) + sum_price(find_items_of_category(c.id)))
    end

    @chartCategories = LazyHighCharts::HighChart.new('bar') do |f|
      f.series(:name=> 'Betrag', :showInLegend => false, :data=> category_amount)
      f.options[:chart][:defaultSeriesType] = "bar"
      f.options[:xAxis] = {:plot_bands => "none", :title=>{:text=>"Kategorien"}, :categories => category_name}
      f.options[:yAxis][:title] = {:text=>"Euro"}
      f.options[:chart][:backgroundColor] = 'rgba(0, 0, 0, 0)'
    end

    respond_with(@categories)
  end

  def show
    respond_with(@category)
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.save
    respond_with(@category)
  end

  def update
    @category.update(category_params)
    respond_with(@category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :notice, :active, :income, :user_id, :glyphicon_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/income_helper.rb
module IncomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/landing_helper.rb
module LandingHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/passthrough_helper.rb
module PassthroughHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
  def find_baskets_in_month(vendor_id)
    Basket.where(:user_id => current_user.id, :vendor_id => vendor_id )
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
    <% if @category.errors.any? %>
        <div id="error_explanation" class="alert fade in alert-danger">
          <h3><%= pluralize(@category.errors.count, "Fehler") %> beim anlegen einer Kategorie:</h3>
          <ul>
            <% @category.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


<div class="panel panel-default">


    <div class="panel-heading">
        <h3 class="panel-title">Anlegen</h3>
    </div>

    <div class="panel-body">

        <div class="col-xs-6">
            <label>Einnahme: </label> <%= f.check_box :income %>
            <%= f.hidden_field :user_id, :value => current_user.id %>
        </div>

        <div class="col-xs-6">
            <div class="form-group">
              <label>Aktiv: </label>
                <%= f.check_box :active %>

            </div>
        </div>

        <div class="col-xs-12">
            <div class="form-group">
                <label class="" for="">Name: </label>
              <div class="input-group">
                <div class="input-group-addon"><i class="fa fa-file-text"></i></div>
                <%= f.text_field :name, :class =>"form-control", :placeholder => "Name" %>
              </div>
            </div>
        </div>


      <div class="col-xs-12">
        <div class="form-group">
          <label class="" for="">Symbol: </label>
          <div class="input-group">
            <%= f.collection_select(:glyphicon_id, Glyphicon.all, :id, :name, {multiple: false}, :class=>'selectpicker')%>
          </div>

        </div>
      </div>


      <div class="col-xs-12">
            <div class="form-group">
                <label class="" for="">Notiz: </label>
              <div class="input-group">
                <div class="input-group-addon"><i class="fa fa-file-text"></i></div>
                <%= f.text_area :notice, :class =>"form-control", :placeholder => "Notiz" %>
              </div>
            </div>
        </div>


    </div>

    <div class="panel-footer">
      <%= f.submit "Speichern" , :class => "btn btn-default" %>
    </div>

</div>

<% end %>

app/views/categories/_list.html.erb
          <div class="list-group">
            <% Category.where(:user_id => current_user.id).each do |category| %>
                <%= link_to category_path(category) do %>
                    <% if !category.active? %>
                        <li class="list-group-item">
                    <% elsif category.income? %>
                        <li class="list-group-item list-group-item-success">
                    <% else %>
                        <li class="list-group-item list-group-item-danger">
                    <% end %>
                    <%= category.name %>
                    <span class="badge pull-right"> <%=sum_price(find_items_of_category(category.id)) %> &euro;</span>
                    </li>
                <% end %>
            <% end %>
          </div>

app/views/categories/edit.html.erb
<div class="page-header">

  <h1> <%= link_to categories_path do %>  <i class="fa fa-arrow-left"></i> <% end %> Kategorie ändern<i class="fa fa-files-o pull-right"></i></h1>

</div>

<%= render 'form' %>

app/views/categories/index.html.erb
<div class="page-header">

    <div class="text-center">
      <h1>

        Kategorie
        <i class="fa fa-files-o pull-right"></i>

      </h1>
    </div>

</div>

<div role="tabpanel">
  <%= link_to '+ Hinzufügen', new_category_path, :class => 'btn btn-success pull-left', :role => 'button' %>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" >
      <a href="#gridIncome" aria-controls="gridIncome" role="tab" data-toggle="tab">
        <i class="fa fa-th"></i> Grid Einnahme
      </a>
    </li>
    <li role="presentation">
      <a href="#gridSpending" aria-controls="gridSpending" role="tab" data-toggle="tab">
        <i class="fa fa-th"></i> Grid Ausgabe
      </a>
    </li>
    <li role="presentation" class="active">
      <a href="#list" aria-controls="list" role="tab" data-toggle="tab">
        <i class="fa fa-bars"></i> List
      </a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <br>
    <div role="tabpanel" class="tab-pane fade " id="gridIncome">

        <% @categories.each do |category| %>
          <% if category.income? %>
            <div class="col-xs-6 col-lg-4">
              <% if (category.active) %>
                    <div class="panel panel-success">
              <% else %>
                  <div class="panel panel-default">
              <% end %>
              <div class="panel-heading">
                <%= link_to category do %>
                <h3 class="panel-title text-center">

                  <%= category.name %>

                </h3>
                <% end %>
              </div>
              <div class="panel-body">
                <div class="text-center">
                  <h4 data-toggle="tooltip" data-placement="bottom" title="Summe der bisherigen Ausgaben beim Händler">  <%=sum_price(find_income_items_of_category(category.id)) %> <i class="fa fa-euro"></i></h4>
                </div>
                <hr>
                <button type="button" class="btn btn-default btn-xs btn-block popover-top" data-toggle="popover" title="Notiz" data-content="<%= category.notice %>"><i class="fa fa-file-text"></i>  Notiz </button>
              </div>
              <div class="panel-footer">
                <% if (category.active) %>
                    <%= link_to edit_category_path(category) do %>  <button class="btn btn-default"> <i class="fa fa-pencil-square-o"></i> Ändern </button> <% end %>
                <% else %>
                    <%= link_to edit_category_path(category) do %>  <button class="btn btn-default"> <i class="fa fa-wrench"></i> Aktivieren </button> <% end %>
                <% end %>
                <%= link_to category, method: :delete, data: { confirm: 'Wollen Sie die Kategorie löschen?' } do %> <button class="btn btn-default"> <i class="fa fa-trash-o"></i> Löschen </button>  <% end %>


              </div>
              </div>
            </div>
              <% end %>
        <% end %>
      </div>

      <div role="tabpanel" class="tab-pane fade" id="gridSpending">

        <% @categories.each do |category| %>
            <% if !category.income? %>


            <div class="col-xs-6 col-lg-4">

              <% if (category.active) %>
                  <div class="panel panel-danger">
              <% else %>
                  <div class="panel panel-default">
              <% end %>



              <div class="panel-heading">
                <%= link_to category do %>
                    <h3 class="panel-title text-center">





                      <%= category.name %>


                    </h3>
                <% end %>
              </div>



              <div class="panel-body">

                <div class="text-center">
                  <h4 data-toggle="tooltip" data-placement="bottom" title="Summe der bisherigen Ausgaben beim Händler">  <%=sum_price(find_items_of_category(category.id)) %> <i class="fa fa-euro"></i></h4>
                </div>
                <hr>

                <button type="button" class="btn btn-default btn-xs btn-block popover-top" data-toggle="popover" title="Notiz" data-content="<%= category.notice %>"><i class="fa fa-file-text"></i>  Notiz </button>
              </div>

              <div class="panel-footer">
                <% if (category.active) %>
                    <%= link_to edit_category_path(category) do %>  <button class="btn btn-default"> <i class="fa fa-pencil-square-o"></i> Ändern </button> <% end %>
                <% else %>
                    <%= link_to edit_category_path(category) do %>  <button class="btn btn-default"> <i class="fa fa-wrench"></i> Aktivieren </button> <% end %>
                <% end %>
                <%= link_to category, method: :delete, data: { confirm: 'Wollen Sie die Kategorie löschen?' } do %> <button class="btn btn-default"> <i class="fa fa-trash-o"></i> Löschen </button>  <% end %>

              </div>

              </div>
              </div>
                <% end %>
        <% end %>
        </div>

        <div role="tabpanel" class="tab-pane fade active in" id="list">
          <div class="col-lg-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Übersicht</h3>
              </div>
              <div class="panel-body">
                <%= high_chart("my_id9", @chartCategories)  %>
              </div>
            </div>


          <div class="list-group">
            <% @categories.each do |category| %>
                <%= link_to category_path(category) do %>
                    <% if !category.active? %>
                        <li class="list-group-item">
                    <% elsif category.income? %>
                        <li class="list-group-item list-group-item-success">
                    <% else %>
                        <li class="list-group-item list-group-item-danger">
                    <% end %>
                    <% if !category.glyphicon.nil? %>
                    <i class="fa <%=category.glyphicon.name%>"></i>
                    <% else%>
                        <i class="fa fa-file-text"></i>
                     <%end%>
                    <%= category.name %>
                    <% if !category.income %>
                    <span class="badge pull-right"> <%=sum_price(find_items_of_category(category.id)) %> &euro;</span>
                    <%else%>
                        <span class="badge pull-right"> <%=sum_price(find_income_items_of_category(category.id)) %> &euro;</span>
                    <%end%>
                    </li>
                <% end %>
            <% end %>
          </div>
        </div>
        </diV>
      </div>
    </div>


<%= link_to '+', new_category_path, :class => 'btn btn-default', :role => 'button' %>

app/views/categories/new.html.erb
<div class="page-header">
  <h1> <%= link_to categories_path do %>  <i class="fa fa-arrow-left"></i> <% end %> Kategorie <i class="fa fa-files-o pull-right"></i> </h1>
</div>

<div class="col-sm-12 col-md-7">
  <%= render 'form' %>
</div>


<div class="col-md-5 hidden-sm hidden-xs">
  <div class="panel panel-default">

    <div class="panel-heading">
      <h3 class="panel-title">Liste</h3>
    </div>

    <div class="panel-body">
  <%= render 'list' %>
    </div>

  </div>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">

  <h1> <%= link_to categories_path do %>  <i class="fa fa-arrow-left"></i> <% end %> Kategorie Details<i class="fa fa-files-o pull-right"></i></h1>

</div>
<div class="col-xs-12">
  <% if (@category.active) %>
      <% if (@category.income) %>
          <div class="panel panel-success">
      <% else %>
          <div class="panel panel-danger">
      <% end %>
  <% else %>
      <div class="panel panel-default">
  <% end %>

  <div class="panel-heading">
    <%= link_to @category do %>
        <h3 class="panel-title text-center">
          <% if (@category.income) %>
              <i class="fa fa-plus pull-left" data-toggle="tooltip" data-placement="left" title="Einnahme"></i>
          <% else %>
              <i class="fa fa-minus pull-left" data-toggle="tooltip" data-placement="left" title="Ausgabe"></i>
          <% end %>

          <%= @category.name %>
          <% if (@category.active) %>
              <i class="fa fa-check pull-right" data-toggle="tooltip" data-placement="left" title="Category ist aktiv"></i>
          <% else %>
              <i class="fa fa-times pull-right" data-toggle="tooltip" data-placement="left" title="Category ist inaktiv"></i>
          <% end %>
        </h3>
    <% end %>
  </div>
      <div class="panel-body">
        <div class="text-center">
          <% if !@category.glyphicon.nil? %>
          <p><i class="fa <%= @category.glyphicon.name%>"></i> <%= @category.notice %></p>
           <% else%>
          <p><i class="fa fa-file-text"></i> <%= @category.notice %></p>
              <%end%>
          </div>

        <div class="table">
            <table class="table table-hover">
              <thead>
                  <tr>
                    <th>Datum</th>
                    <th>Name</th>
                    <th>Notiz</th>
                    <th>Anzahl</th>
                    <th>Preis</th>
                  </tr>
              </thead>
              <tbody>
              <% if (@category.income) %>

                  <% find_income_items_of_category(@category.id).each do |item| %>
                      <tr onclick="location.href='/items/<%= item.id %>'">
                        <td><%= item.launch %></td>
                        <td><%= item.name %></td>
                        <td><%= item.notice %></td>
                        <td><%= item.quantity %></td>
                        <td><%= item.price  %> &euro;</td>
                      </tr>
                  <% end %>
              <% else %>
                  <% find_items_of_category(@category.id).each do |item| %>
                      <tr onclick="location.href='/items/<%= item.id %>'">
                        <td><%= item.launch %></td>
                        <td><%= item.name %></td>
                        <td><%= item.notice %></td>
                        <td><%= item.quantity %></td>
                        <td><%= item.price  %> &euro;</td>
                      </tr>
                  <% end %>
              <% end %>
              <tr>
                <td colspan="4"><strong>Summe:</strong></td>
                <td> <% if (@category.income) %>
                      <%= sum_price(find_income_items_of_category(@category.id)) %> &euro;
                      <%else %>
                      <%= sum_price(find_items_of_category(@category.id)) %> &euro;
                <%end%>
                      </td>
              </tr>
              </tbody>
            </table>
        </div>
      </div>
    <div class="panel-footer">

      <%= link_to categories_path do %> <button class="btn btn-default btn-xs"> <i class="fa fa-arrow-left"></i> Zurück </button> <% end %>
      <%= link_to edit_category_path(@category) do %> <button class="btn btn-default btn-xs"> <i class="fa fa-pencil-square-o"></i> Ändern </button> <% end %>

    </div>
  </div>
</div>